name: Update Discord Analytics

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Analytics Image
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-analytics.png
          config_output: png
          base: header, traffic
          plugin_traffic: yes
